python -m training.main \
    --save-frequency 1 \
    --zeroshot-frequency 1 \
    --report-to tensorboard \
    --train-data="/ds/documents/IIT-CDIP"  \
    --val-data="/ds/documents/IIT-CDIP"  \
    --warmup 10000 \
    --batch-size=128 \
    --lr=1e-3 \
    --wd=0.1 \
    --epochs=30 \
    --workers=8 \
    --model RN50 \
    --test-run 1 \
    --dataset-type custom \